/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CaixaCreditoController;
import javax.swing.JTextField;

/**
 *
 * @author topga
 */
public class CaixaCreditoView extends javax.swing.JFrame {

    private final CaixaCreditoController controller;

    /**
     * Creates new form CaixaCreditoView
     */
    public CaixaCreditoView() {
        initComponents();
        controller = new CaixaCreditoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldIdDoPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeDoCliente = new javax.swing.JTextField();
        jTextFieldNomeDoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldValorUnitarioDoProduto = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDesconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldParcelas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creditos - GML");
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Crédito");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 45, -1, -1));

        jTextFieldIdDoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdDoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdDoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 159, 111, -1));

        jLabel2.setText("ID do pedido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 127, -1, -1));

        jLabel3.setText("Cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 199, -1, -1));

        jTextFieldNomeDoCliente.setEditable(false);
        jTextFieldNomeDoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeDoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeDoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 227, 250, -1));

        jTextFieldNomeDoProduto.setEditable(false);
        getContentPane().add(jTextFieldNomeDoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 291, 200, -1));

        jLabel4.setText("Produto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 263, -1, -1));

        jLabel5.setText("Quantidade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 327, -1, -1));

        jTextFieldQuantidade.setEditable(false);
        getContentPane().add(jTextFieldQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 359, 68, -1));

        jLabel6.setText("Valor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 401, -1, -1));

        jTextFieldValorUnitarioDoProduto.setEditable(false);
        getContentPane().add(jTextFieldValorUnitarioDoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 429, 110, -1));

        jTextFieldTotal.setEditable(false);
        getContentPane().add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 359, 100, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Total:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 357, -1, -1));

        jTextFieldDesconto.setEditable(false);
        getContentPane().add(jTextFieldDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 227, 54, -1));

        jLabel8.setText("Desconto %:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 199, -1, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 155, -1, -1));

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 429, -1, -1));

        jLabel9.setText("Parcelas:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 263, -1, -1));
        getContentPane().add(jTextFieldParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 291, 54, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GML logo.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 490, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdDoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdDoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdDoPedidoActionPerformed

    private void jTextFieldNomeDoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeDoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeDoClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         controller.buscandoDadosDoBancoUtilizandoOIdCliente();
         controller.operacoesMatematicas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         controller.utiliandoOInsert();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaixaCreditoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaixaCreditoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaixaCreditoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaixaCreditoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaixaCreditoView().setVisible(true);
            }
        });
    }

    public JTextField getjTextFieldDesconto() {
        return jTextFieldDesconto;
    }

    public void setjTextFieldDesconto(JTextField jTextFieldDesconto) {
        this.jTextFieldDesconto = jTextFieldDesconto;
    }

    public JTextField getjTextFieldIdDoPedido() {
        return jTextFieldIdDoPedido;
    }

    public void setjTextFieldIdDoPedido(JTextField jTextFieldIdDoPedido) {
        this.jTextFieldIdDoPedido = jTextFieldIdDoPedido;
    }

    public JTextField getjTextFieldNomeDoCliente() {
        return jTextFieldNomeDoCliente;
    }

    public void setjTextFieldNomeDoCliente(JTextField jTextFieldNomeDoCliente) {
        this.jTextFieldNomeDoCliente = jTextFieldNomeDoCliente;
    }

    public JTextField getjTextFieldNomeDoProduto() {
        return jTextFieldNomeDoProduto;
    }

    public void setjTextFieldNomeDoProduto(JTextField jTextFieldNomeDoProduto) {
        this.jTextFieldNomeDoProduto = jTextFieldNomeDoProduto;
    }

    public JTextField getjTextFieldQuantidade() {
        return jTextFieldQuantidade;
    }

    public void setjTextFieldQuantidade(JTextField jTextFieldQuantidade) {
        this.jTextFieldQuantidade = jTextFieldQuantidade;
    }

    public JTextField getjTextFieldTotal() {
        return jTextFieldTotal;
    }

    public void setjTextFieldTotal(JTextField jTextFieldTotal) {
        this.jTextFieldTotal = jTextFieldTotal;
    }

    public JTextField getjTextFieldValorUnitarioDoProduto() {
        return jTextFieldValorUnitarioDoProduto;
    }

    public JTextField getjTextFieldParcelas() {
        return jTextFieldParcelas;
    }

    public void setjTextFieldParcelas(JTextField jTextFieldParcelas) {
        this.jTextFieldParcelas = jTextFieldParcelas;
    }

    public void setjTextFieldValorUnitarioDoProduto(JTextField jTextFieldValorUnitarioDoProduto) {
        this.jTextFieldValorUnitarioDoProduto = jTextFieldValorUnitarioDoProduto;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldDesconto;
    private javax.swing.JTextField jTextFieldIdDoPedido;
    private javax.swing.JTextField jTextFieldNomeDoCliente;
    private javax.swing.JTextField jTextFieldNomeDoProduto;
    private javax.swing.JTextField jTextFieldParcelas;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldValorUnitarioDoProduto;
    // End of variables declaration//GEN-END:variables
}
