CREATE TABLE ACESSO (
	ID SERIAL NOT NULL,
	USUARIO VARCHAR(20) NOT NULL,
	SENHA VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID, USUARIO)
)

CREATE TABLE CADASTRO_DE_CLIENTE(
	
	ID SERIAL NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	RG VARCHAR(9) NOT NULL, 
	NASCIMENTO VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(100),
	PRIMARY KEY(CPF)

)

CREATE TABLE SMARTPHONES (
	
	ID SERIAL NOT NULL,
	IDCATEGORIA INTEGER NOT NULL,
	NOME_DO_PRODUTO VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(20) NOT NULL,
	VALOR DOUBLE PRECISION NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (IDCATEGORIA) REFERENCES ID_DAS_CATEGORIAS (IDCATEGORIA)
	
)

CREATE TABLE ACESSORIOS (
	
	ID SERIAL NOT NULL,
	IDCATEGORIA INTEGER NOT NULL,
	NOME_DO_PRODUTO VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(20) NOT NULL,
	VALOR DOUBLE PRECISION NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (IDCATEGORIA) REFERENCES ID_DAS_CATEGORIAS (IDCATEGORIA)
	
)


CREATE TABLE HARDWARES (
	
	ID SERIAL NOT NULL,
	IDCATEGORIA INTEGER NOT NULL,
	NOME_DO_PRODUTO VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(20) NOT NULL,
	VALOR DOUBLE PRECISION NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (IDCATEGORIA) REFERENCES ID_DAS_CATEGORIAS (IDCATEGORIA)
		
)

CREATE TABLE CONSOLES (
	
	ID SERIAL NOT NULL,
	IDCATEGORIA INTEGER NOT NULL,
	NOME_DO_PRODUTO VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(20) NOT NULL,
	VALOR DOUBLE PRECISION NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (IDCATEGORIA) REFERENCES ID_DAS_CATEGORIAS (IDCATEGORIA)
	
)

CREATE TABLE JOGOS (
	
	ID SERIAL NOT NULL,
	IDCATEGORIA INTEGER NOT NULL,
	NOME_DO_PRODUTO VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(20) NOT NULL,
	VALOR DOUBLE PRECISION NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (IDCATEGORIA) REFERENCES ID_DAS_CATEGORIAS (IDCATEGORIA)
	
)

CREATE TABLE ID_DAS_CATEGORIAS (
	IDCATEGORIA INTEGER NOT NULL,
	PRIMARY KEY (IDCATEGORIA)
)

CREATE TABLE ITENSPORCLIENTES(
	
	ID_DO_PEDIDO SERIAL NOT NULL,
	ID_CATEGORIA INTEGER NOT NULL,
	CPF_ITENS VARCHAR(11) NOT NULL,
	NOME_DO_PRODUTO VARCHAR(100) NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	VALOR DOUBLE PRECISION NOT NULL,
	DESCONTO INTEGER NOT NULL,
	PRIMARY KEY (ID_DO_PEDIDO),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES ID_DAS_CATEGORIAS (IDCATEGORIA),
	FOREIGN KEY (CPF_ITENS) REFERENCES CADASTRO_DE_CLIENTE (CPF)
	
)

CREATE TABLE CAIXA (

	ID_DO_PEDIDO_FK INTEGER NOT NULL,
	PAGAMENTO VARCHAR NOT NULL,
	STATUS VARCHAR NOT NULL,
	FOREIGN KEY (ID_DO_PEDIDO_FK) REFERENCES ITENSPORCLIENTES (ID_DO_PEDIDO)
	
)














